# Generated by Django 5.1.3 on 2024-11-07 23:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MaqLin', models.CharField(max_length=3, verbose_name='Maquina ou Linha')),
                ('Setor', models.CharField(max_length=20, verbose_name='Setor')),
                ('Linha', models.CharField(max_length=20, verbose_name='Linha')),
                ('Obs', models.CharField(max_length=30, verbose_name='Observações')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FK_Local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.local', verbose_name='Local')),
            ],
        ),
        migrations.CreateModel(
            name='Leituras',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ValorA', models.FloatField(verbose_name='Valor Lido A')),
                ('ValorB', models.FloatField(verbose_name='Valor Lido B')),
                ('Data', models.DateTimeField(verbose_name='Data da Leitura')),
                ('FK_Sensor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sensores.sensor', verbose_name='Sensor')),
            ],
        ),
    ]
